# Generated by devtools/yamaker.

LIBRARY()

LICENSE(LicenseRef-scancode-swig)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(4.2.1)

ORIGINAL_SOURCE(https://github.com/swig/swig/archive/v4.2.1.tar.gz)

ADDINCL(
    GLOBAL FOR
    swig
    contrib/tools/swig/Lib/python
    GLOBAL FOR
    swig
    contrib/tools/swig/Lib
)

END()
