# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(MIT)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(3.8.1)

ORIGINAL_SOURCE(https://github.com/ToruNiina/toml11/archive/v3.8.1.tar.gz)

NO_RUNTIME()

NO_UTIL()

END()
