# Generated by devtools/yamaker/ym2 from nixpkgs 24.05.

LIBRARY()

LICENSE(MIT)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(4.4.0)

ORIGINAL_SOURCE(https://github.com/ToruNiina/toml11/archive/v4.4.0.tar.gz)

NO_RUNTIME()

NO_UTIL()

END()
