# Generated by devtools/yamaker.

LIBRARY()

VERSION(1.2.3)

WITHOUT_LICENSE_TEXTS()

LICENSE(MIT)

IF (ARCH_X86_64)
    ADDINCL(
        GLOBAL contrib/libs/musl/arch/x86_64
    )
ENDIF()

IF (ARCH_AARCH64)
    ADDINCL(
        GLOBAL contrib/libs/musl/arch/aarch64
    )
ENDIF()

ADDINCL(
    GLOBAL contrib/libs/musl/arch/generic
    GLOBAL contrib/libs/musl/include
    GLOBAL contrib/libs/musl/extra
)

NO_PLATFORM()

NO_RUNTIME()

LD_PLUGIN(musl.py)

END()
