# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(1.20)

LICENSE(MIT)

ADDINCL(
    devtools/ymake/contrib/python-rapidjson/rapidjson/include
)

NO_COMPILER_WARNINGS()

NO_LINT()

SRCS(
    rapidjson.cpp
)

PY_REGISTER(
    rapidjson
)

RESOURCE_FILES(
    PREFIX devtools/ymake/contrib/python-rapidjson/
    .dist-info/METADATA
    .dist-info/top_level.txt
    rapidjson/license.txt
    rapidjson/readme.md
)

END()

RECURSE_FOR_TESTS(
    tests
)
