# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

VERSION(1.34.0)

ORIGINAL_SOURCE(https://github.com/chriskohlhoff/asio/archive/asio-1-34-0.tar.gz)

LICENSE(
    BSL-1.0 AND
    Public-Domain
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/openssl
)

ADDINCL(
    GLOBAL contrib/libs/asio/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

CFLAGS(
    GLOBAL -DASIO_STANDALONE
    GLOBAL -DASIO_SEPARATE_COMPILATION
)

IF (MSVC)
    CFLAGS(
        GLOBAL -DASIO_HAS_STD_COROUTINE
        GLOBAL -DASIO_HAS_CO_AWAIT
    )
ENDIF()

SRCS(
    src/asio.cpp
    src/asio_ssl.cpp
)

END()

RECURSE(
    src/examples
)
