run_last_command:
	echo 'Executing {{ command }}' >&2
	cd {{ repro_sources_path }} && \
	python3 execute_ya.py inputs/last_command.json --trunk-revision {{ trunk_revision }} {% if patch_file %} --patch-path revisions/diff.patch {% endif %}
{% if configure %}
run_last_command_configure:
	echo 'Generating graph for {{ command }}' >&2
	cd {{ repro_sources_path }} && \
	python3 execute_ya.py inputs/last_command_configure.json --trunk-revision {{ trunk_revision }} {% if patch_file %} --patch-path revisions/diff.patch {% endif %}
{% endif %}

{% if has_ymake_calls %}
{% for call in ymake_calls %}
ymake_run_{{ call }}:
	echo 'Generating graph for {{ command }}' >&2
	echo 'Warning! Please, note that chaches will be re-generated. Result may has diffrence if problem is cache-specific.'
	cd {{ repro_sources_path }} && \
	python3 execute_ya.py inputs/last_command.json --trunk-revision {{ trunk_revision }} {% if patch_file %} --patch-path revisions/diff.patch --repeat-ymake-run {{call}} {% endif %}
{% endfor %}
{% endif %}

{% for target in package_targets %}
{{ target }}:
	echo 'Building {{ target }}' >&2
	cd {{ repro_sources_path }} && \
	python3 execute_ya.py inputs/{{ target }}.json --trunk-revision {{ trunk_revision }} {% if patch_file %} --patch-path revisions/diff.patch {% endif %}

{{ target }}_configure:
	echo 'Generating graph for {{ target }}' >&2
	cd {{ repro_sources_path }} && \
	python3 execute_ya.py inputs/{{ target }}_configure.json --trunk-revision {{ trunk_revision }} {% if patch_file %} --patch-path revisions/diff.patch {% endif %}
{% endfor %}
