# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(17.1.1)

LICENSE(MIT)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    path/__init__.py
    path/classes.py
    path/compat/py38.py
    path/masks.py
    path/matchers.py
)

RESOURCE_FILES(
    PREFIX contrib/python/path/
    .dist-info/METADATA
    .dist-info/top_level.txt
    path/py.typed
)

END()
