DISTBUILD_PRIORITY_FACTOR = 1000 * 1000 * 10
DISTBUILD_PRIORITY_DELTA = 200 * 1000

DISTBUILD_HIGH_CACHE_HIT_PRIORITY_DELTA = DISTBUILD_PRIORITY_DELTA
DISTBUILD_MEDIUM_CACHE_HIT_PRIORITY_DELTA = -1 * int(DISTBUILD_PRIORITY_DELTA / 2)
DISTBUILD_LOW_CACHE_HIT_PRIORITY_DELTA = -2 * int(DISTBUILD_PRIORITY_DELTA / 2)
DISTBUILD_POSTCOMMITS_PRIORITY_DELTA = -3 * int(DISTBUILD_PRIORITY_DELTA / 2)
DISTBUILD_LARGE_TESTS_PRIORITY_DELTA = -4 * int(DISTBUILD_PRIORITY_DELTA / 2)
DISTBUILD_FAST_CHECK_PRIORITY_DELTA = DISTBUILD_HIGH_CACHE_HIT_PRIORITY_DELTA + 100


class DistbuildClusterType(object):
    PRODUCTION, TESTING = range(2)


class DistbuildRepoType(object):
    TARED, SVN, AAPI, ARCC = range(4)


def calc_dist_priority(priority_factor, revision, priority_delta=0):
    return priority_factor * DISTBUILD_PRIORITY_FACTOR - (revision - priority_delta)
