DEFAULT_SANDBOX_URL = 'https://sandbox.yandex-team.ru'
DEFAULT_SANDBOX_PROXY_URL = 'https://proxy.sandbox.yandex-team.ru'
DONE_STATUSES = ('TIMEOUT', 'SUCCESS', 'STOPPED', 'EXCEPTION', 'DELETED', 'FAILURE', 'NO_RES', 'RELEASED')
SUCCESSFULLY_DONE_STATUSES = ('SUCCESS', 'RELEASED')
SUSPENDED_STATUSES = ('SUSPENDED',)
